[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_coordinator = "CafKDt5dyrYHFC2KUaJU2ux6AXEc2oFAjtdUoNaktwVX"
reasoning_registry = "87CGxPABDUwvSRzByXeMcmZ5Qo8B6225z2q8D8VkxUjt"
threat_intelligence = "Fo9Nm41pvuUCT2sPPsuo1XyWCQCTKf6GNwASQ1ZMEfpv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallets/guardian-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
